---
title: "贝格尔医学检验实验室"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
        - { title: "主页", href: "/BEAGLE_LIMS", align: left }
        - { title: "实验上机", href: "run.Rmd", align: left }
        - { title: "检测管理", href: "test.Rmd", align: left }
        - { title: "人员实验", href: "user.Rmd", align: left }
        - { title: "权限管理", href: "permission.Rmd", align: left }
        - { title: "仪器管理", href: "instrument.Rmd", align: left }
        - { title: "标本管理", href: "specimen.Rmd", align: left }
        - { title: "nCoV报告", href: "nCoV2.Rmd", align: left }
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(DBI)
library(dplyr)
library(tibble)
library(openxlsx)
library(shinyjs)
library(RMySQL)
source("share.R")

```

PCR实验室悬挂紫外灯使用记录
=====================================  

Column {.sidebar data-width=350}
-----------------------------------------------------------------------

```{r}
TABLE = "PCR_ziwai"

rv <- reactiveValues(table = limsdbReadTable(TABLE))

## 主窗口表格内容
mainTbl_sql <- "SELECT id `记录号`, room `房间`, date `日期`, time `消毒时间`, length `消毒时长(h)`,
                       total `累计时间`, status `仪器状态`,
                       u.name `操作人`, DATE_FORMAT(p.updatetime, '%m-%d %H:%i') `更新日期`
                 FROM `PCR_ziwai` p
                 LEFT JOIN `User` u on u.userKey = p.operator
                 ORDER BY p.updatetime DESC"

rv$mainTbl <- limsdbGetQuery(mainTbl_sql)

infer_total <- isolate(rv$table %>% pull(total) %>% max())

```

***

```{r}
useShinyjs(rmd=TRUE)

numericInput("id", label = "记录号（新增记录时此处留空）", value = NA, min = 1)

selectInput("room", label = "房间号", choices = 101:108, selected = 102)

dateInput("date", label = "日期", value = Sys.Date())

textInput("time", "开机时间", value = format(Sys.time(), "%R"))

numericInput("length", label = "消毒时长(h)", value = 1)

numericInput("total", label = "累计时长(h)", value = infer_total)

selectInput("status", "仪器状态", choices = c("正常", "异常"), selected = "正常")

selectInput("operator", label = "操作人", choices = get_user_list(), selected = 366169)

actionButton("submit", label = "新增/更新")

query_id <- "id"

update_ary <- c("room", "date", "time", "length", "total", "status", "operator")

tags$span(" ")

actionButton("delete", "删除")

tags$span(" ")

actionButton("clear", "清空")

tags$hr()

textInput("report_room", label = "报告房间", value = "102")

textInput("report_month", label = "报告月份（格式：yyyy-mm）", value = format(Sys.Date(), "%Y-%m"))

# 直接用downloadButton不工作，此处代码参考https://stackoverflow.com/questions/55345498/downloadbutton-width-in-r-flexdashboard/55374600#55374600

uiOutput("downloadUI")

output$downloadUI <- renderUI( {
  downloadButton('report', '下载报告')
})

output$report <- downloadHandler(filename = function() {
    paste0('PCR实验室悬挂紫外灯使用记录表_', input$report_room, "_",format(Sys.Date(), "%Y-%m"), '.xlsx')
  },
  content = function(file) {
      ## fill in report template
      template_file <- "pcr_ziwai/ziwai1.xlsx"
      wb <- loadWorkbook(template_file)
      
      writeData(wb, sheet = 1, x = format(Sys.Date(), "%Y年%m月"), startCol = 1, startRow = 2)
      writeData(wb, sheet = 1, x = input$report_room, startCol = 4, startRow = 2)
  
      sql <- paste0("select DATE_FORMAT(date, '%d') date, time, length, total, status, u.name operator
                    from PCR_ziwai p
                    left join User u on u.userKey = p.operator
                    where DATE_FORMAT(date, '%Y-%m') = '", input$report_month, "'
                    and room = '", input$report_room, "'")
      records <- limsdbGetQuery(sql) %>% mutate(date = as.integer(date))
      
      if (nrow(records) > 0) {
        for (i in 1:nrow(records)) {
          row_num <- 3+records$date[i]
          writeData(wb, sheet = 1, x = records$time[i], startCol = 2, startRow = row_num)
          writeData(wb, sheet = 1, x = records$length[i], startCol = 3, startRow = row_num)
          writeData(wb, sheet = 1, x = records$total[i], startCol = 4, startRow = row_num)
          writeData(wb, sheet = 1, x = records$status[i], startCol = 5, startRow = row_num)
          writeData(wb, sheet = 1, x = records$operator[i], startCol = 6, startRow = row_num)
        }
      }
      saveWorkbook(wb, file = file, overwrite = TRUE)
    }
)

## focus input element
jscode <- 'shinyjs.refocus = function(e_id) {document.getElementById(e_id).focus();}'
extendShinyjs(text = jscode)

output$mainTbl <- renderDT(rv$mainTbl, rownames= FALSE)

observeEvent(input[[query_id]],{
  if (!is.na(input[[query_id]])) {
    for (field in update_ary) {
      updateTextInput(session, field, value = rv$table %>%
                      filter(get(query_id) == input[[query_id]]) %>%
                      pull(field))
    }
  }

})

check_id <- function(date, room) {
  query_sql <- paste0("select * from PCR_ziwai where date = '", date, "' and room = '", room, "'")
  r <- limsdbGetQuery(query_sql)
  if (nrow(r) == 1) return(r$id)
  else return(0)
}

# 新增与更新

observeEvent(input$submit, {
  print("OK")
  ## Single-bracket indexing of reactivevalues object is not allowed.
  ## So isolate it first
  inputs <- isolate(reactiveValuesToList(input))

  # serialNumber <- ifelse(input$serialNumber == "", "NULL", input$serialNumber)
  inputs$date <- ifelse(toString(inputs$date) == "", "NULL", toString(inputs$date))

  ## missing id
  if ( is.na(inputs[query_id]) ) {
    inputs[query_id] <- check_id(inputs$date, inputs$room)
  }
  submitValues <- paste(paste("'", inputs[c(query_id, update_ary)], "'", sep = "", collapse = ", " ), "now()", sep = ", ")

  insert_sql <- paste("INSERT INTO `", TABLE, "` VALUES (", submitValues, ") ON DUPLICATE KEY UPDATE ",
                      paste("`", update_ary, "` = '", inputs[update_ary], "'", sep = "", collapse = ", "), sep = "")

  insert_sql <- gsub("'NULL'", "NULL", insert_sql)
  rv$sql_exe <- limsdbExecute(insert_sql)

  ## 刷新主表格内容
  rv$mainTbl <- limsdbGetQuery(mainTbl_sql)
  rv$table <- limsdbReadTable(TABLE)
  
  # 如果记录编号为空，则更新自动生成的记录编号，方便接着更新/删除这条记录
  if (is.na(input[[query_id]])) {
    updateTextInput(session, query_id, value = rv$table %>%
                        slice(n()) %>%
                        pull(query_id))
  }
})

# 删除记录

observeEvent(input$delete, {
  print(input[[query_id]])
  if (!is.na(input[[query_id]])) {
    delete_sql <- paste("DELETE FROM `", TABLE, "` WHERE `", query_id, "` = '", input[[query_id]], "'", sep = "")
    rv$sql_exe <- limsdbExecute(delete_sql)
  
    ## 刷新主表格内容
    rv$mainTbl <- limsdbGetQuery(mainTbl_sql)
    rv$table <- limsdbReadTable(TABLE)
  }
})

observeEvent(input$clear, {

  updateTextInput(session, query_id, value = NA)

  ## 清空完focus在样本编号输入框
  js$refocus(query_id)
  
})
```


Column {data-width=450}
-----------------------------------------------------------------------

### 记录表101

```{r}
DT::dataTableOutput("mainTbl")
```

Column {data-width=200}
-----------------------------------------------------------------------

### 使用说明

1. 使用人必须按使用手册进行操作，如发现异常情况及时按程序报告；			
2. 使用人按照使用表格认真填写。
