---
title: "贝格尔医学检验实验室"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(DBI)
library(dplyr)
library(tibble)
library(shinyjs)
library(plotly)

# operation id
UPDATEID = 3
INSERTID = 2
DELETEID = 4

mydb <- dbConnect(RMySQL::MySQL(), dbname='BEAGLE_LIMS', username='lims',
                  password='lims', host='192.168.253.178', port=3306)
dbSendQuery(mydb,"SET NAMES utf8")

get_select_list <- function(table, key_col, value_col) {
  sel_tbl <- as_tibble(DBI::dbReadTable(mydb, table))
  sel_lst <- as.list(sel_tbl %>% pull(value_col))
  names(sel_lst) <- sel_tbl %>% pull(key_col)
  return(sel_lst)
}
```

实验上机
=====================================  

Column {.sidebar data-width=350}
-----------------------------------------------------------------------

最后更新日期：`r file.mtime("run.Rmd")`

```{r}
TABLE = "Run"

rv <- reactiveValues(permission = list(view = FALSE, insert = FALSE, delete = FALSE),
                     table = as_tibble(DBI::dbReadTable(mydb, TABLE)))
## 主窗口表格内容
mainTbl_sql <- "SELECT r.id `记录号`, t.title `检测项目`, date `实验日期`, experimentNumber `实验号`,
                s.specimenNumber `标本编号`, s.name `标本姓名`, r.userId `实验员号`,
                u.name `实验员姓名`, r.updatetime `更新时间`
                 FROM `Run` r
                 LEFT JOIN `Test` t on t.testNumber = r.testNumber
                 LEFT JOIN `Specimen` s on s.specimenNumber = r.specimenNumber
                 LEFT JOIN `User` u on u.userKey = r.userId"
rv$mainTbl <- dbGetQuery(mydb, mainTbl_sql)

passwordInput("userKey", label = "用户钥匙", value = NA)
textOutput("p")
```

***

```{r}
useShinyjs(rmd=TRUE)

numericInput("id", label = "记录编号", value = NA, min = 1)

selectInput("testNumber", label = "检测项目", choices = get_select_list("`Test`", "title", "testNumber"))

dateInput("date", label = "实验日期", value = Sys.Date())

textInput("experimentNumber", label = "实验号")

textInput("specimenNumber", label = "标本号")

textInput("specimenName", label = "标本姓名")

textInput("userId", label = "实验员号")

textInput("userName", label = "实验员姓名")

actionButton("submit", label = "新增/更新")

query_id <- "id" ## primary id

update_ary <- c("testNumber", "date", "experimentNumber", "specimenNumber", "userId")
hide_ary <- c("testNumber", "date", "experimentNumber", "specimenNumber", "userId", "specimenName", "userName")

specimenName_lst <- get_select_list("`Specimen`", "specimenNumber", "name")
userName_lst <- get_select_list("`User`", "userKey", "name")

tags$span(" ")

actionButton("delete", "删除")

observeEvent(input$userKey, {
  # 查询用户permission
  if (grepl("^\\d+$", input$userKey)) {
    user_sql <- paste("SELECT u.`userKey`, u.`name` `name`, o.`chinese` `permission`, t.`name` tname, p.isValid
                FROM `Permission` p
                LEFT JOIN `User` u on p.userId = u.userKey
                LEFT JOIN `Operation` o on p.`operationId` = o.`id`
                LEFT JOIN `Table` t on p.`tableId` = t.`id`
                WHERE t.`name` = '", TABLE, "'
                AND u.isValid = 1
                AND u.`userKey` = ", input$userKey, sep = "")
    rv$user <- dbGetQuery(mydb, user_sql)
  } else {
    rv$user <- tibble(userKey = integer(), permission = character())
  }

  permissions <- rv$user %>% filter(userKey == input$userKey, isValid == 1) %>%
                         pull(permission)
  rv$permission[["view"]] <- ifelse("查询" %in% permissions, TRUE, FALSE)
  rv$permission[["delete"]] <- ifelse("删除" %in% permissions, TRUE, FALSE)
  rv$permission[["insert"]] <- ifelse("新增" %in% permissions, TRUE, FALSE)

  output$p <- renderText(paste("用户权限：", paste(permissions, collapse = "、")))

  if (rv$permission[["view"]] == TRUE) {
      output$mainTbl <- renderDT(rv$mainTbl, options =
                                   list(pageLength = 15, autoWidth = TRUE), rownames= FALSE)
      output$logText <- renderPrint(rv$log_text)
      output$chartA <- renderPlotly(plot_ly(rv$mainTbl %>%
                                              group_by(`检测项目`) %>%
                                              summarise(Num = length(`检测项目`)),
                                            x = ~`检测项目`, y = ~`Num`, type = "bar"))
  } else {
    output$mainTbl <- renderDT(tibble())
    output$logText <- renderPrint("")
    output$chartA <- renderPlotly(plot_ly(type = "bar"))
  }

  if (rv$permission[["delete"]]) {
    show("delete")
  } else {
    hide("delete")
  }
  
  for(ele in c(query_id, hide_ary, "submit")) {
    if (rv$permission[["insert"]]) {
      show(ele)
    } else {
      hide(ele)
    }
  }
  
})

observeEvent(input[[query_id]], {
  
  if (rv$permission[["view"]]) {
    for (field in update_ary) {
      updateTextInput(session, field, value = rv$table %>%
                      filter(get(query_id) == input[[query_id]]) %>%
                      pull(field))
    }
  } else {
    renderText("用户权限不足")
  }

})

observeEvent(input$userId, {
  if (input$userId %in% names(userName_lst)) {
    updateTextInput(session, "userName", value = userName_lst[[input$userId]])
  } else {
    updateTextInput(session, "userName", value = "")
  }
})

observeEvent(input$specimenNumber, {
  if (input$specimenNumber %in% names(specimenName_lst)) {
    updateTextInput(session, "specimenName", value = specimenName_lst[[input$specimenNumber]])
  } else {
    updateTextInput(session, "specimenName", value = "")
  }
})

observeSample <- function(testNumber, date, experimentNumber) {
  o_sql <- paste("SELECT id, specimenNumber, userId
                 FROM `Run`
                 WHERE testNumber = '", testNumber, "'
                 AND   date = '", date, "'
                 AND   experimentNumber = '", experimentNumber, "'", sep = "")
  dbGetQuery(mydb, o_sql)
}

observeEvent({input$testNumber; input$date; input$experimentNumber}, {
  os <- observeSample(input$testNumber, toString(input$date), input$experimentNumber)
  if (nrow(os) == 1) {
    updateTextInput(session, "id", value = os$id[1])
    updateTextInput(session, "specimenNumber", value = os$specimenNumber[1])
    updateTextInput(session, "userId", value = os$userId[1])
  }
})

get_table_id <- function(table) {
  # get table id using table name
  table_sql <- paste("SELECT `id` FROM `Table` WHERE `name` = '", table, "'", sep = "")
  table_rv <- dbGetQuery(mydb, table_sql)
  if (nrow(table_rv) == 0) {
    stop("Table not found!")
  } else {
    return(table_rv$id[1])
  }
}

# 日志记录查询

get_log <- function(table) {
  log_sql <- paste("SELECT u.name name, o.chinese operation, t.chinese `table`, recordId, `timestamp` `time`
  FROM Log l
  LEFT JOIN `User` u on u.userKey = l.userKey
  LEFT JOIN `Operation` o on l.operationId = o.id
  LEFT JOIN `Table` t on l.tableId = t.id
  WHERE t.name = '", table, "'
  ORDER BY `timestamp` DESC", sep = "")
  
  log_tbl <- dbGetQuery(mydb, log_sql)
  
  if (nrow(log_tbl) > 0) {
    paste(log_tbl$name, "于", log_tbl$time, "在", log_tbl$table, "中", log_tbl$operation, "了第", log_tbl$recordId,"号记录", sep = "")
  } else {
    return("无操作记录")
  }
}

rv$log_text <- get_log(TABLE)

## 新增与更新

observeEvent(input$submit, {
  ## Single-bracket indexing of reactivevalues object is not allowed.
  ## So isolate it first
  inputs <- isolate(reactiveValuesToList(input))
  validate(
    for (ele in update_ary) {
      need(input[[eval(ele)]], '请输入信息')
    }
  )
  ## NULL value manipulation
  # serialNumber <- ifelse(input$serialNumber == "", "NULL", input$serialNumber)
  inputs$date <- ifelse(toString(input$date) == "", "NULL", toString(input$date))
  
  ## missing id
  if ( is.na(inputs$id) ) {
    inputs$id <- 0
  }
  submitValues <- paste(paste("'", inputs[c(query_id, update_ary)], "'", sep = "", collapse = ", " ), "now()", sep = ", ")
  
  insert_sql <- paste("INSERT INTO `", TABLE, "` VALUES (", submitValues, ") ON DUPLICATE KEY UPDATE ",
                      paste("`", update_ary, "` = '", inputs[update_ary], "'", sep = "", collapse = ", "), sep = "")
  insert_sql <- gsub("'NULL'", "NULL", insert_sql)
  rv$sql_exe <- dbExecute(mydb, insert_sql)

  # 添加日志
  
  if (input[[query_id]] %in% rv$table[[query_id]]) {
    log_values <- paste(input$userKey, get_table_id(TABLE), UPDATEID,
                  paste("'", input[[query_id]] ,"'", sep = ""),
                  sep = ", ")
  } else {
    log_values <- paste(input$userKey, get_table_id(TABLE), INSERTID,
                  paste("'", input[[query_id]] ,"'", sep = ""),
                  sep = ", ")
  }
  log_ins_sql <- paste("INSERT INTO `Log`(`userKey`, `tableId`, `operationId`, `recordId`, `values`, `timestamp`) VALUES (", log_values, ", \"", submitValues, "\" , now())", sep = "")
  dbExecute(mydb, log_ins_sql)
  
  ## 刷新主表格内容
  rv$log_text <- get_log(TABLE)
  rv$mainTbl <- dbGetQuery(mydb, mainTbl_sql)
  rv$table <- as_tibble(DBI::dbReadTable(mydb, TABLE))
})

# 删除记录

observeEvent(input$delete, {
  delete_sql <- paste("DELETE FROM `", TABLE, "` WHERE `", query_id, "` = '", input[[query_id]], "'", sep = "")
  rv$sql_exe <- dbExecute(mydb, delete_sql)
  
  # 添加日志
  
  log_values <- paste(input$userKey, get_table_id(TABLE), DELETEID,
                  paste("'", input[[query_id]] ,"'", sep = ""),
                  sep = ", ")

  log_ins_sql <- paste("INSERT INTO `Log`(`userKey`, `tableId`, `operationId`, `recordId`, `values`, `timestamp`) VALUES (", log_values, ", '', now())", sep = "")
  dbExecute(mydb, log_ins_sql)
  
  ## 刷新主表格内容
  rv$log_text <- get_log(TABLE)
  rv$mainTbl <- dbGetQuery(mydb, mainTbl_sql)
  rv$table <- as_tibble(DBI::dbReadTable(mydb, TABLE))
})

```


Column {data-width=450}
-----------------------------------------------------------------------

### 权限列表

```{r}
DT::dataTableOutput("mainTbl")
```

Column {data-width=200}
-----------------------------------------------------------------------

### 操作日志

```{r}
verbatimTextOutput("logText")

```

### 汇总计数

```{r}
plotlyOutput("chartA")
```

