---
title: "贝格尔医学检验实验室"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
        - { title: "主页", href: "/BEAGLE_LIMS", align: left }
        - { title: "实验上机", href: "run.Rmd", align: left }
        - { title: "检测管理", href: "test.Rmd", align: left }
        - { title: "人员实验", href: "user.Rmd", align: left }
        - { title: "权限管理", href: "permission.Rmd", align: left }
        - { title: "仪器管理", href: "instrument.Rmd", align: left }
        - { title: "标签管理", href: "label.Rmd", align: left }
        - { title: "nCoV报告", href: "nCoV2.Rmd", align: left }
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(DBI)
library(dplyr)
library(tibble)
library(shinyjs)
library(plotly)
library(RMySQL)
source("share.R")

# killDbConnections()

# operation id
UPDATEID = 3
INSERTID = 2
DELETEID = 4

mydb <- dbConnect(RMySQL::MySQL(), dbname='BEAGLE_LIMS', username='lims',
                  password='lims', host='192.168.253.178', port=3306)
dbSendQuery(mydb,"SET NAMES utf8")

```

标本管理
=====================================  

Column {.sidebar data-width=350}
-----------------------------------------------------------------------

最后更新日期：`r file.mtime("specimen.Rmd")`

```{r}
TABLE = "Specimen"

rv <- reactiveValues(permission = list(view = FALSE, insert = FALSE, delete = FALSE),
                     table = as_tibble(DBI::dbReadTable(mydb, TABLE)))
## 主窗口表格内容
mainTbl_sql <- "SELECT specimenNumber `标本编号`, name `姓名`, gender `性别`, age `年龄`,
                       specimenType `标本类型`,
                       contactNumber `联系方式`, institution `送检单位`, originalNumber `原始编号`,
                       collectDate `采集日期`,
                       updatetime `更新日期`
                 FROM `Specimen`
                 ORDER BY `更新日期` DESC"
rv$mainTbl <- dbGetQuery(mydb, mainTbl_sql)

inferDate <- as.Date(as.POSIXct(as.numeric(Sys.time()) - 3600*4, origin="1970-01-01"))

passwordInput("userKey", label = "用户钥匙", value = NA)
textOutput("p")
```

***

```{r}
useShinyjs(rmd=TRUE)

textInput("specimenNumber", label = "标本编号")

textInput("name", label = "姓名")

selectInput("gender", label = "性别", choices = c("女", "男", "-"))

textInput("age", label = "年龄")

selectInput("specimenType", label = "标本类型", choices = c("咽拭子", "鼻咽拭子", "手术组织", "穿刺组织", "全血",
                                    "血浆", "血清", "尿液", "粪便", "分泌物", "呕吐物",
                                    "唾液", "脑脊液", "淋巴液", "房水","其他"))

selectInput("specimenStatus", label = "标本状态", choices = c("符合要求", "溶血", "污染", "损坏",
                                                        "时间过久", "量较少"))

textInput("medicalNumber", label = "病案号")

textInput("institution", label = "送检单位")

textInput("contactNumber", label = "联系电话")

textInput("originalNumber", label = "原始编号")

textInput("doctor", label = "送检医师")

dateInput("collectDate", label = "采集日期（注意是否隔日）", value = inferDate)

dateInput("receiveDate", label = "接受日期（注意是否隔日）", value = inferDate)

actionButton("submit", label = "新增/更新")

query_id <- "specimenNumber"

update_ary <- c("name", "gender", "age", "specimenType", "specimenStatus", "medicalNumber", "institution", "contactNumber", "originalNumber", "doctor", "collectDate", "receiveDate")

tags$span(" ")

actionButton("delete", "删除")

tags$span(" ")

actionButton("clear", "清空")

## focus input element
jscode <- 'shinyjs.refocus = function(e_id) {document.getElementById(e_id).focus();}'
extendShinyjs(text = jscode)

observeEvent(input$userKey, {
  ## 打开时就focus在userKey输入框
  js$refocus("userKey")
  # 查询用户permission
  if (grepl("^\\d+$", input$userKey)) {
    user_sql <- paste("SELECT u.`userKey`, u.`name` `name`, o.`chinese` `permission`, t.`name` tname, p.isValid
                FROM `Permission` p
                LEFT JOIN `User` u on p.userId = u.userKey
                LEFT JOIN `Operation` o on p.`operationId` = o.`id`
                LEFT JOIN `Table` t on p.`tableId` = t.`id`
                WHERE t.`name` = '", TABLE, "'
                AND u.isValid = 1
                AND u.`userKey` = ", input$userKey, sep = "")
    rv$user <- dbGetQuery(mydb, user_sql)
  } else {
    rv$user <- tibble(userKey = integer(), permission = character())
  }

  permissions <- rv$user %>% filter(userKey == input$userKey, isValid == 1) %>%
                         pull(permission)
  rv$permission[["view"]] <- ifelse("查询" %in% permissions, TRUE, FALSE)
  rv$permission[["delete"]] <- ifelse("删除" %in% permissions, TRUE, FALSE)
  rv$permission[["insert"]] <- ifelse("新增" %in% permissions, TRUE, FALSE)

  output$p <- renderText(paste("用户权限：", paste(permissions, collapse = "、")))

  if (rv$permission[["view"]] == TRUE) {
      output$mainTbl <- renderDT(rv$mainTbl, options =
                                   list(pageLength = 15, autoWidth = TRUE, scrollX = TRUE), rownames= FALSE)
      output$logText <- renderPrint(rv$log_text)
      output$chartA <- renderPlotly(plot_ly(rv$mainTbl %>%
                                              group_by(`标本类型`) %>%
                                              summarise(Num = length(`标本类型`)),
                                            x = ~`标本类型`, y = ~`Num`, type = "bar"))
  } else {
    output$mainTbl <- renderDT(tibble())
    output$logText <- renderPrint("")
    output$chartA <- renderPlotly(plot_ly(type = "bar"))
  }

  if (rv$permission[["delete"]]) {
    showElement("delete")
  } else {
    hideElement("delete")
  }
  
  for(ele in c(query_id, update_ary, "submit")) {
    if (rv$permission[["insert"]]) {
      showElement(ele)
    } else {
      hideElement(ele)
    }
  }
  
  if (rv$permission[["insert"]]) {
    js$refocus("specimenNumber")
  }

})

observeEvent(input[[query_id]],{
  
  if (rv$permission[["view"]]) {
    for (field in update_ary) {
      updateTextInput(session, field, value = rv$table %>%
                      filter(get(query_id) == input[[query_id]]) %>%
                      pull(field))
      if (rv$table %>% filter(get(query_id) == input[[query_id]]) %>% nrow == 0) {
        # try use label module to inspect institution and contact number once no records in specimen table
        updateTextInput(session, "institution",
                      value = label_query(mydb, specNum = input[[query_id]], returnKey = "source"))
        updateTextInput(session, "contactNumber",
                      value = label_query(mydb, specNum = input[[query_id]], returnKey = "contactNumber"))
      }
    }
  } else {
    renderText("用户权限不足")
  }

})

get_table_id <- function(table) {
  # get table id using table name
  table_sql <- paste("SELECT `id` FROM `Table` WHERE `name` = '", table, "'", sep = "")
  table_rv <- dbGetQuery(mydb, table_sql)
  if (nrow(table_rv) == 0) {
    stop("Table not found!")
  } else {
    return(table_rv$id[1])
  }
}

# 日志记录查询

get_log <- function(table) {
  log_sql <- paste("SELECT u.name name, o.chinese operation, t.chinese `table`, recordId, `timestamp` `time`
  FROM Log l
  LEFT JOIN `User` u on u.userKey = l.userKey
  LEFT JOIN `Operation` o on l.operationId = o.id
  LEFT JOIN `Table` t on l.tableId = t.id
  WHERE t.name = '", table, "'
  ORDER BY `timestamp` DESC", sep = "")
  
  log_tbl <- dbGetQuery(mydb, log_sql)
  
  if (nrow(log_tbl) > 0) {
    paste(log_tbl$name, "于", log_tbl$time, "在", log_tbl$table, "中", log_tbl$operation, "了第", log_tbl$recordId,"号记录", sep = "")
  } else {
    return("无操作记录")
  }
}

rv$log_text <- get_log(TABLE)

# 新增与更新

observeEvent(input$submit, {
  ## Single-bracket indexing of reactivevalues object is not allowed.
  ## So isolate it first
  inputs <- isolate(reactiveValuesToList(input))
  validate(
    for (ele in update_ary) {
      need(input[[eval(ele)]], '请输入信息')
    }
  )
  # serialNumber <- ifelse(input$serialNumber == "", "NULL", input$serialNumber)
  inputs$collectDate <- ifelse(toString(input$collectDate) == "", "NULL", toString(input$collectDate))
  inputs$receiveDate <- ifelse(toString(input$receiveDate) == "", "NULL", toString(input$receiveDate))
  
  submitValues <- paste(paste("'", inputs[c(query_id, update_ary)], "'", sep = "", collapse = ", " ), "now()", sep = ", ")
  
  insert_sql <- paste("INSERT INTO `", TABLE, "` VALUES (", submitValues, ") ON DUPLICATE KEY UPDATE ",
                      paste("`", update_ary, "` = '", inputs[update_ary], "'", sep = "", collapse = ", "), sep = "")

  insert_sql <- gsub("'NULL'", "NULL", insert_sql)
  rv$sql_exe <- dbExecute(mydb, insert_sql)
  
  # 添加日志
  
  if (input[[query_id]] %in% rv$table[[query_id]]) {
    log_values <- paste(input$userKey, get_table_id(TABLE), UPDATEID,
                  paste("'", input[[query_id]] ,"'", sep = ""),
                  sep = ", ")
  } else {
    log_values <- paste(input$userKey, get_table_id(TABLE), INSERTID,
                  paste("'", input[[query_id]] ,"'", sep = ""),
                  sep = ", ")
  }
  log_ins_sql <- paste("INSERT INTO `Log`(`userKey`, `tableId`, `operationId`, `recordId`, `values`, `timestamp`) VALUES (", log_values, ", \"", submitValues, "\" , now())", sep = "")

  dbExecute(mydb, log_ins_sql)

  ## 刷新主表格内容
  rv$log_text <- get_log(TABLE)
  rv$mainTbl <- dbGetQuery(mydb, mainTbl_sql)
  rv$table <- as_tibble(DBI::dbReadTable(mydb, TABLE))
})

# 删除记录

observeEvent(input$delete, {
  delete_sql <- paste("DELETE FROM `", TABLE, "` WHERE `", query_id, "` = '", input[[query_id]], "'", sep = "")
  rv$sql_exe <- dbExecute(mydb, delete_sql)

  # 添加日志

  log_values <- paste(input$userKey, get_table_id(TABLE), DELETEID,
                  paste("'", input[[query_id]] ,"'", sep = ""),
                  sep = ", ")

  log_ins_sql <- paste("INSERT INTO `Log`(`userKey`, `tableId`, `operationId`, `recordId`, `values`, `timestamp`) VALUES (", log_values, ", '', now())", sep = "")

  dbExecute(mydb, log_ins_sql)
  
  ## 刷新主表格内容
  rv$log_text <- get_log(TABLE)
  rv$mainTbl <- dbGetQuery(mydb, mainTbl_sql)
  rv$table <- as_tibble(DBI::dbReadTable(mydb, TABLE))
})

observeEvent(input$clear, {

  updateTextInput(session, "specimenNumber", value = as.integer(input$specimenNumber) + 1)

  ## 清空完focus在样本编号输入框
  js$refocus("specimenNumber")
  
})
```


Column {data-width=450}
-----------------------------------------------------------------------

### 项目列表

```{r}
DT::dataTableOutput("mainTbl")
```

Column {data-width=200}
-----------------------------------------------------------------------

### 操作日志

```{r}
verbatimTextOutput("logText")
```

### 汇总计数

```{r}
plotlyOutput("chartA")
```
