---
title: "贝格尔医学检验实验室"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
        - { title: "主页", href: "/BEAGLE_LIMS", align: left }
        - { title: "实验上机", href: "run.Rmd", align: left }
        - { title: "标本管理", href: "specimen.Rmd", align: left }
        - { title: "检测管理", href: "test.Rmd", align: left }
        - { title: "仪器管理", href: "instrument.Rmd", align: left }
        - { title: "权限管理", href: "permission.Rmd", align: left }
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(DBI)
library(dplyr)
library(tibble)
library(shinyjs)
library(plotly)
source("share.R")

```

人员管理
=====================================  

Column {.sidebar data-width=350}
-----------------------------------------------------------------------

最后更新日期：`r file.mtime("user.Rmd")`

```{r}
TABLE = "User"

rv <- reactiveValues(permission = list(view = FALSE, insert = FALSE, delete = FALSE),
                     table = limsdbReadTable(TABLE))

passwordInput("userKey", label = "用户钥匙", value = NA)
textOutput("p")
```

***

```{r}
useShinyjs(rmd=TRUE)

numericInput("userId", label = "用户钥匙", value = NA, min = 1)

textInput("name", label = "姓名")

textInput("department", label = "部门", value = NA)

selectInput("isValid", label = "是否有效", choices = list("是" = 1, "否" = 0))

actionButton("submit", label = "新增/更新")

tags$span(" ")

actionButton("delete", "删除")

observeEvent(input$userKey, {
  # 查询用户permission
  if (grepl("^\\d+$", input$userKey)) {
    user_sql <- paste("SELECT u.`userKey`, u.`name` `name`, o.`chinese` `permission`, t.`name` tname, p.isValid
                FROM `Permission` p
                LEFT JOIN `User` u on p.userId = u.userKey
                LEFT JOIN `Operation` o on p.`operationId` = o.`id`
                LEFT JOIN `Table` t on p.`tableId` = t.`id`
                WHERE t.`name` = '", TABLE, "'
                AND u.isValid = 1
                AND u.`userKey` = ", input$userKey, sep = "")
    rv$user <- limsdbGetQuery(user_sql)
  } else {
    rv$user <- tibble(userKey = integer(), permission = character())
  }

  # print(rv$user)
  # permissions <- userKeys %>% filter(userKey == input$userKey) %>% pull(permission)
  permissions <- rv$user %>% filter(userKey == input$userKey, isValid == 1) %>%
                         pull(permission)
  rv$permission[["view"]] <- ifelse("查询" %in% permissions, TRUE, FALSE)
  rv$permission[["delete"]] <- ifelse("删除" %in% permissions, TRUE, FALSE)
  rv$permission[["insert"]] <- ifelse("新增" %in% permissions, TRUE, FALSE)

  output$p <- renderText(paste("用户权限：", paste(permissions, collapse = "、")))

  if (rv$permission[["view"]]) {
    output$mainTbl <- renderDT(rv$table)
    output$logText <- renderPrint(rv$log_text)
    output$chartA <- renderPlotly(plot_ly(rv$table %>% group_by(department) %>% summarise(Num = length(department)),
                     x = ~`department`, y = ~`Num`, type = "bar"))
  } else {
    output$mainTbl <- renderDT(tibble())
    output$logText <- renderPrint("")
    output$chartA <- renderPlotly(plot_ly(type = "bar"))
  }

  if (rv$permission[["delete"]]) {
    showElement("delete")
  } else {
    hideElement("delete")
  }
  
  if (rv$permission[["insert"]]) {
    # enable("submit")
    showElement("userId")
    showElement("name", anim = T)
    showElement("department")
    showElement("isValid")
    showElement("submit")
  } else {
    # disable("submit")
    hideElement("userId")
    hideElement("name")
    hideElement("department")
    hideElement("isValid")
    hideElement("submit")
  }
  
})

observeEvent(input$userId,{
  
  if (rv$permission[["view"]]) {
    for (field in c("name", "department", "isValid")) {
      updateTextInput(session, field, value = rv$table %>%
                      filter(userKey == input$userId) %>%
                      pull(field))
    }
  } else {
    renderText("用户权限不足")
  }

})

get_table_id <- function(table) {
  # get table id using table name
  table_sql <- paste("SELECT `id` FROM `Table` WHERE `name` = '", table, "'", sep = "")
  table_rv <- limsdbGetQuery(table_sql)
  if (nrow(table_rv) == 0) {
    stop("Table not found!")
  } else {
    return(table_rv$id[1])
  }
}

# 日志记录查询

rv$log_text <- get_log(TABLE)

# 新增与更新

observeEvent(input$submit, {
  validate(
    need(input$name, '请输入姓名'),
    need(input$department, '请输入部门')
  )
  # serialNumber <- ifelse(input$serialNumber == "", "NULL", input$serialNumber)
  # dateCommissioned <- ifelse(toString(input$dateCommissioned) == "", "NULL", toString(input$dateCommissioned))
  submitValues <- paste(input$userId, ", '", paste(input$name,
                  input$department, sep = "', '"), "',", input$isValid, ", now()", sep = "")
  insert_sql <- paste("INSERT INTO `", TABLE, "` VALUES (", submitValues, ") ON DUPLICATE KEY UPDATE
          name = '", input$name, "',
          department = '", input$department, "',
          isValid = '", input$isValid, "'", sep = "")
  # insert_sql <- gsub("'NULL'", "NULL", insert_sql)
  rv$sql_exe <- limsdbExecute(insert_sql)
  
  # 添加日志
  
  if (input$userId %in% rv$table$userKey) {
    log_values <- paste(input$userKey, get_table_id(TABLE), UPDATEID,
                  input$userId, sep = ", ")
  } else {
    log_values <- paste(input$userKey, get_table_id(TABLE), INSERTID,
                  input$userId, sep = ", ")
  }
  log_ins_sql <- paste("INSERT INTO `Log`(`userKey`, `tableId`, `operationId`, `recordId`, `values`, `timestamp`) VALUES (", log_values, ", \"", submitValues, "\" , now())", sep = "")
  limsdbExecute(log_ins_sql)
  rv$log_text <- get_log(TABLE)
  
  rv$table <- limsdbReadTable(TABLE)
})

# 删除记录

observeEvent(input$delete, {
  delete_sql <- paste("DELETE FROM `", TABLE, "` WHERE `userKey` = ", input$userId, sep = "")
  rv$sql_exe <- limsdbExecute(delete_sql)
  
  # 添加日志
  
  log_values <- paste(input$userKey, get_table_id(TABLE), DELETEID,
                input$userId, sep = ", ")

  log_ins_sql <- paste("INSERT INTO `Log`(`userKey`, `tableId`, `operationId`, `recordId`, `values`, `timestamp`) VALUES (", log_values, ", '', now())", sep = "")
  limsdbExecute(log_ins_sql)
  rv$log_text <- get_log(TABLE)
  
  rv$table <- limsdbReadTable(TABLE)
  
})

```


Column {data-width=450}
-----------------------------------------------------------------------

### 人员列表

```{r}
DT::dataTableOutput("mainTbl")
```

Column {data-width=200}
-----------------------------------------------------------------------

### 操作日志

```{r}
verbatimTextOutput("logText")

```

### 汇总计数

```{r}
plotlyOutput("chartA")
```

