---
title: "贝格尔医学检验实验室"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
        - { title: "主页", href: "/BEAGLE_LIMS", align: left }
        - { title: "实验上机", href: "run.Rmd", align: left }
        - { title: "标本管理", href: "specimen.Rmd", align: left }
        - { title: "检测管理", href: "test.Rmd", align: left }
        - { title: "人员实验", href: "user.Rmd", align: left }
        - { title: "权限管理", href: "permission.Rmd", align: left }
        - { title: "仪器管理", href: "instrument.Rmd", align: left }
runtime: shiny
---

```{r setup, include=FALSE}
# Author: Zhao Rui
# Date: 2020-02-20
library(flexdashboard)
library(shinyMatrix)
library(dplyr)
library(DBI)
library(plotly)
library(readxl)
library(stringr)
library(purrr)
library(tidyr)
library(officer)
library(ggplot2)
source("share.R")

killDbConnections()

mydb <- dbConnect(RMySQL::MySQL(), dbname='BEAGLE_LIMS', username='lims',
                  password='lims', host='192.168.253.178', port=3306)
dbSendQuery(mydb,"SET NAMES utf8")

addResourcePath("www", "www")

POS_CTRL = 'p'
NEG_CTRL = 'n'

report_template_pos <- "report/nCoV_template3.docx"
report_template_neg <- "report/nCoV_template4.docx"

```

之江生物Z-RR-0479结果分析（测试）
=====================================  

Column {.sidebar data-width=1000}
-----------------------------------------------------------------------

**上海之江生物2019-nCoV检测试剂盒 QuantStudioDx PCR实验结果Excel数据数据分析** [使用说明书下载](www/Z-RR-0479-02_User_manual.pdf)
最后更新日期：`r file.mtime("ZRR0479.Rmd")`

```{r}

rv <- reactiveValues(specimenMatrix = matrix(),
                     speTbl = as_tibble(DBI::dbReadTable(mydb, 'Specimen')),
                     runTbl = as_tibble(DBI::dbReadTable(mydb, 'Run')),
                     nCoVTbl = as_tibble(DBI::dbReadTable(mydb, 'nCoV')),
                     reportStatus = "",
                     dir = paste0("report/", format(Sys.time(), "%Y%m%d%H%M")))

tags$link(rel = 'stylesheet', type = 'text/css', href = 'www/style.css')

# textInput("reportNumber", label = "报告起始编号（按Panel从上到下、从左到右的样本结果顺序依次编号）",
#           value = paste0("P04", format(Sys.Date(), "%y%m%d"), "01"))

uiOutput("ui")

output$ui <- renderUI( {
  matrixInput(
        inputId = "layout",
        label = "样本排列记录表（每孔对应位置填写已登记的实验号）",
        value = matrix(nrow = 8, ncol = 12, dimnames = list(LETTERS[1:8], 1:12)),
        class = "character",
        cols = list(
          names = TRUE
        ),
        rows = list(
          names = TRUE
        ),
        copy = TRUE,
        paste = TRUE
  )
})

dateInput("testDate", label = "实验日期/检测日期", value = Sys.Date())

fileInput("qdx_xlsx", label = "选择QDx PCR导出Excel文件",
          buttonLabel = "打开",
          placeholder = ".xlsx file", accept = c(".xlsx"))

dateInput("reportDate", label = "报告日期", value = Sys.Date())

userNames <- get_select_list("`User`", "name", "userKey")

selectInput("tester", label = "检测员", choices = userNames, selected = 277895)

selectInput("checker", label = "审核员", choices = userNames, selected = 122953)

selectInput("isRerun", label = "是否是重分析", choices = list("是" = 1, "否" = 0), selected = 0)

actionButton("submit", "生成报告")

renderText(rv$reportStatus)

tags$hr()

# 直接用downloadButton不工作，此处代码参考https://stackoverflow.com/questions/55345498/downloadbutton-width-in-r-flexdashboard/55374600#55374600

uiOutput("downloadUI")

output$downloadUI <- renderUI( {
  downloadButton('report', '下载报告')
})

output$report <- downloadHandler(filename = function() {
     paste0('nCoV-', Sys.Date(), '.zip')
  },
  content = function(file) {
      file.copy(paste0(rv$dir, ".zip"), file)
    }
)

# 根据输入的实验号排版信息，在右侧显示对应样本号

expNum2speNum <- function(expNum) {
  if (expNum == '') {
    return(NA)
  }
  if (grepl("^p", tolower(expNum)) ) return(POS_CTRL)
  if (grepl("^n", tolower(expNum)) ) return(NEG_CTRL)
  filTbl <- rv$runTbl %>% filter(experimentNumber == as.integer(expNum), date == toString(input$testDate), testNumber == 'P04')
  if (nrow(filTbl) == 1) {
    return(filTbl$specimenNumber)
  } else if (nrow(filTbl) > 1) {
    return("重复")
  } else {
    return("未知")
  }
}

layout2specimen <- function(mat) {
  spe <- mat
  for (i in 1:nrow(mat)) {
    for (j in 1:ncol(mat)) {
      spe[i,j] <- expNum2speNum(mat[i,j])
    }
  }
  return(spe)
}

observeEvent({input$testDate; input$layout}, {
  rv$specimenMatrix <- layout2specimen(input$layout)
})

# 读取Excel结果，及扩增数据

tbl_res <- reactive({
  if (is.null(input$qdx_xlsx)) {
    tibble(`Well` = integer(), `Well Position` = character(),
           Omit = character(), `Sample Name`=character(),
           `Target Name` = character(),	Task = character(),
           Reporter = character(),	Quencher = character(),	CT = numeric())
  } else {
    read_excel(input$qdx_xlsx$datapath, sheet = "Results", skip = 40)
    # 调试数据
    # tbl_res <- read_excel("/var/share/QuantStudioDx/2019-nCoV/2020-3-2/2020-03-02 ZJ-2019nCoV_data.xlsx", sheet = "Results", skip = 40)
  }
})

tbl_amp <- reactive({
  if (is.null(input$qdx_xlsx)) {
    tibble(Well = integer(), `Delta Rn` = numeric(), `Cycle` = integer())
  } else {
    read_excel(input$qdx_xlsx$datapath, sheet = "Amplification Data", skip = 40,
               col_types = c("numeric", "text", "text", "skip", "numeric"))
    # 调试数据
    # tbl_amp <- read_excel("/var/share/QuantStudioDx/2019-nCoV/2020-3-2/2020-03-02 ZJ-2019nCoV_data.xlsx", sheet = "Amplification Data", skip = 40)
  }
})

drn_ylim <- reactive({
  if (nrow(tbl_amp()) == 0) {
    1
  } else {
    max(tbl_amp()$`Delta Rn`, na.rm = T) + 0.1
  }
  # 调试数据
  # drn_ylim <- max(tbl_amp$`Delta Rn`, na.rm = T) + 0.1
})

tbl_amp_smp <- reactive({
  if (is.null(input$qdx_xlsx)) {
    tibble(Cycle = integer(), `Delta Rn` = numeric(), `Sample Name` = integer())
  } else {
    tbl_amp() %>% left_join(tbl_res() %>% select(`Well`, `Sample Name`) %>% distinct()) %>%
      mutate(Cycle = as.integer(Cycle)) %>% filter(!is.na(`Sample Name`))
  }
  # 调试数据
  # tbl_amp_smp <- tbl_amp %>% left_join(tbl_res %>% select(`Well`, `Sample Name`) %>% distinct()) %>% mutate(Cycle = as.integer(Cycle)) %>% filter(!is.na(`Sample Name`))
})

tbl_amp_pn <- reactive({
  if (nrow(tbl_amp_smp()) == 0) {
    tibble(`Well` = integer(), Cycle = integer(),
           Sample = character(), `Target Name` = character(),
           `p` = numeric(), `n` = numeric())
  } else {
    tbl_amp_smp() %>%
      filter(grepl("p|n", tolower(`Sample Name`))) %>%
      # rowid_to_column() %>%
      spread(`Sample Name`, `Delta Rn`)
      # select(-1) %>%
  }
  # 调试数据
  # tbl_amp_pn <- tbl_amp_smp %>% filter(grepl("p|n", tolower(`Sample Name`))) %>% spread(`Sample Name`, `Delta Rn`)
})

CT2Res <- function(CT, CT_CUTOFF = 43) {
  if (is.na(CT)) return("-")
  if (CT <= CT_CUTOFF) {
    return("+")
  } else {
    return("-")
  }
}

Result <- function(ORF1ab, N, E, D) {
  # 根据ABCD通道CT值判定结果
  if (all(ORF1ab == "+", N == "+", E == "+") ) return("检出")
  if (all(ORF1ab == "+", N == "+", E == "-") ) return("检出")
  if (all(ORF1ab == "+", N == "-", E == "+") ) return("检出")
  if (all(ORF1ab == "+", N == "-", E == "-") ) return("可疑结果")
  if (all(ORF1ab == "-", N == "+", E == "-") ) return("可能为近源冠状病毒")
  if (all(ORF1ab == "-", N == "-", E == "+") ) return("可能为近源冠状病毒")
  if (all(ORF1ab == "-", N == "-", E == "-") ) return("未检出")
  
}

speNum2Info <- function(speNum) {
  filTbl <- rv$speTbl %>% filter(specimenNumber == speNum)
  if (nrow(filTbl) == 1) {
    return(as.list(filTbl))
  } else {
    return("错误")
  }
}

observeEvent(input$submit, {
  rv$reportStatus <- "开始分析数据"
  samples <- unique(tbl_res()$`Sample Name`)
  samples <- samples[!grepl("p|n", samples, ignore.case = TRUE)]
  withProgress(message = '开始分析数据...',
               detail = '依次分析所有样本结果...', value = 0, {
                for (sample in samples) {
                  specimenNumber <- expNum2speNum(sample)
                  
                  # draw amplification plot
                  amp_data <- tbl_amp_smp() %>% filter(`Sample Name` == sample)
                  
                  # plot_ly(amp_data,
                  #   y = ~`Delta Rn`, x= ~`Cycle`, color = ~`Target Name`,
                  #   type = "scatter",
                  #   mode = "lines+markers") %>%
                  #   layout(legend = list(x = 0.1, y = 0.9))
                  
                  amp_fig <- ggplot(amp_data, aes(`Cycle`, `Delta Rn`, color = `Target Name`)) +
                    geom_line() +
                    geom_point() +
                    theme_bw() +
                    theme(legend.background = element_rect(fill=alpha('white', 0)),
                          legend.position = c(0.15, 0.75))

                  ORF1ab <- tbl_res() %>%
                    filter(`Sample Name` == sample, `Target Name` == 'A') %>%
                    pull(`CT`) %>% CT2Res()
                  N <- tbl_res() %>%
                    filter(`Sample Name` == sample, `Target Name` == 'B') %>%
                    pull(`CT`) %>% CT2Res()
                  E <- tbl_res() %>%
                    filter(`Sample Name` == sample, `Target Name` == 'C') %>%
                    pull(`CT`) %>% CT2Res()
                  D <- tbl_res() %>%
                    filter(`Sample Name` == sample, `Target Name` == 'D') %>%
                    pull(`CT`) %>% CT2Res()
                  
                  result <- Result(ORF1ab, N, E, D)
                  
                  testerName <- names(userNames[userNames == input$tester])
                  
                  reporterName <- names(userNames[userNames == input$checker])
                  
                  reportPrefix <- paste0("P04", specimenNumber)
                  
                  reportRecord <- rv$nCoVTbl %>% filter(grepl(reportPrefix, `reportNumber`)) %>%
                                    arrange(reportNumber) %>% slice(n()) %>% pull(reportNumber)
                  if (is_empty(reportRecord) ) {
                    reportVer <- 1
                  } else if (input$isRerun == 1) {
                    reportVer <- str_sub(reportRecord, -1, -1)
                  } else {
                    reportVer <- str_sub(reportRecord, -1, -1) %>% as.integer() + 1
                  }
                  reportNumber <- paste0("P04", specimenNumber, reportVer)
                  
                  speInfo <- speNum2Info(specimenNumber)
                  
                  rv$reportStatus <- paste(rv$reportStatus, sample)
                  
                  # 写入到Word报告中
                  dir.create(rv$dir)
                  
                  # 将靶点结果写完整
                  ORF1ab <- paste0("RdPR基因（", ORF1ab, "）")
                  N <- paste0("N基因（", N, "）")
                  E <- paste0("E基因（", E, "）")
                  
                  if (result == "未检出") {
                    report_template = report_template_neg
                  } else {
                    report_template = report_template_pos
                  }
                  
                  rpt <- read_docx(report_template) %>%
                  body_replace_all_text("xingming", speInfo$name, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("xingbie", speInfo$gender, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("nianling", speInfo$age, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("yangbenleixing", speInfo$specimenType, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("yangbenzhuangtai", speInfo$specimenStatus, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("weiyibaioshi", speInfo$specimenNumber, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("binganhao", speInfo$medicalNumber, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("songjiandanwei", speInfo$institution, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("yuanshibianhao", speInfo$originalNumber, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("yishi", speInfo$doctor, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("caijiriqi", speInfo$collectDate, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("jieshouriqi", speInfo$receiveDate, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("bgbianhao", reportNumber, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("jiancejieguo", result, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("rdpr_result", ORF1ab, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("n_result", N, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("e_result", E, only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("jianceriqi", toString(input$testDate), only_at_cursor = FALSE, fixed = FALSE) %>%
                  body_replace_all_text("baogaoriqi", toString(input$reportDate), only_at_cursor = FALSE, fixed = FALSE)
                  
                  file <- paste0(rv$dir, "/", reportNumber, ".docx")
                  fig_file <- paste0(rv$dir, "/", reportNumber, ".png")
                  print(rpt, target = file)
                  png(filename = fig_file, width = 1200, height = 900, res = 150)
                  print(amp_fig)
                  dev.off()
                  
                  # insert database record for each report
                  # table cols:
                  # reportNumber	specimenNumber	ORF1ab	N	E	result	testDate	reportDate	tester	checker	updatetime
                  ins_sql <- paste0("INSERT INTO `nCoV` VALUES('",
                                    paste(reportNumber, specimenNumber, ORF1ab, N, E, result, input$testDate,
                                    input$reportDate, input$tester, input$checker, sep = "', '"),
                                    "', NOW()) ON DUPLICATE KEY UPDATE
                                    specimenNumber = '", specimenNumber, "',
                                    ORF1ab = '", ORF1ab, "',
                                    N = '", N, "',
                                    E = '", E, "',
                                    result = '", result, "',
                                    testDate = '", input$testDate, "',
                                    reportDate = '", input$reportDate, "',
                                    tester = '", input$tester, "',
                                    checker = '", input$checker, "',
                                    updatetime = NOW()")
                  print(ins_sql)
                  dbExecute(mydb, ins_sql)
                  
                  incProgress(1/length(samples), specimenNumber)
                }
               })
  zip(paste0(rv$dir, ".zip"), rv$dir)
  rv$reportStatus <- paste(rv$reportStatus, "完毕")
})

```

Column {data-width=200}
-----------------------------------------------------------------------

### 样本编号确认（"未知"标识改实验号未找到对应样本编号，"重复"表示同一天内该项目有多个重复实验号）

```{r}
renderTable(rv$specimenMatrix)
```

### 阳性对照品扩增曲线

```{r}
pos_ctrl_text <- reactive(
  if (tbl_res() %>% filter(`Sample Name` == POS_CTRL, grepl("A|B|C", `Target Name`)) %>% pull(CT) %>% is.na() %>% any()) {
    "异常：阳性对照品A/B/C有未扩增"
  } else {
    if ((tbl_res() %>% filter(`Sample Name` == POS_CTRL, grepl("A|B|C", `Target Name`)) %>% pull(CT) > 30) %>% any()) {
      "异常：阳性对照品CT > 30"
    } else {
      "阳性对照品结果正常"
    }
  }
)

pos_ctrl_color <- reactive(
  if (grepl("异",neg_ctrl_text())) {
    "red"
  } else {
    "green"
  }
)

pos_ctrl_ann_lst <- reactive({
  list(
    x = 20,
    y = drn_ylim()*0.27,
    text = pos_ctrl_text()[1],
    font = list(color = pos_ctrl_color()),
    xref = "x",
    yref = "y",
    align = 'left',
    showarrow = FALSE
  )
})

renderPlotly(
  plot_ly(tbl_amp_pn(),
        y = ~get(POS_CTRL), x= ~`Cycle`, color = ~`Target Name`,
        type = "scatter",
        # name = '阳性质控',
        text = ~`Target Name`,
        mode = "lines+markers",
        hovertemplate = paste(
          "<b>Target: %{text}</b><br><br>",
          "%{yaxis.title.text}: %{y:.3f}<br>",
          "%{xaxis.title.text}: %{x:d}<br>",
          "<extra></extra>"
          )) %>%
    layout(legend = list(x = 0.1, y = 0.9),
          annotations = pos_ctrl_ann_lst())
)
```

### 阴性对照品扩增曲线

```{r}
neg_ctrl_text <- reactive(
  if (tbl_res() %>% filter(`Sample Name` == NEG_CTRL, grepl("A|B|C", `Target Name`)) %>% pull(CT) %>% is.na() %>% all()) {
    if (tbl_res() %>% filter(`Sample Name` == NEG_CTRL, grepl("D", `Target Name`)) %>% pull(CT) %>% is.na() %>% any()) {
      "异常：阴性对照品D通道有未扩增"
    } else {
      "阴性对照品结果正常"
    }
  } else {
    "异常：阴性对照品A/B/C通道有扩增"
  }
)

neg_ctrl_color <- reactive(
  if (grepl("异",neg_ctrl_text())) {
    "red"
  } else {
    "green"
  }
)

neg_ctrl_ann_lst <- reactive({
  list(
    x = 20,
    y = drn_ylim()*0.27,
    text = neg_ctrl_text()[1],
    font = list(color = neg_ctrl_color()),
    xref = "x",
    yref = "y",
    align = 'left',
    showarrow = FALSE
  )
})

renderPlotly(
  plot_ly(tbl_amp_pn(),
        y = ~get(NEG_CTRL), x= ~`Cycle`, color = ~paste(`Target Name`, `Well`),
        type = "scatter",
        text = ~`Target Name`,
        mode = "lines+markers",
        hovertemplate = paste(
          "<b>Target: %{text}</b><br><br>",
          "%{yaxis.title.text}: %{y:.3f}<br>",
          "%{xaxis.title.text}: %{x:d}<br>",
          "<extra></extra>"
          )) %>%
    layout(legend = list(x = 0.1, y = 0.9),
          annotations = neg_ctrl_ann_lst())
)
```


          
          